name: CI Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5 # https://docs.astral.sh/uv/guides/integration/github/
        with:
          # Install a specific version of uv
          version: "0.6.2"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Cache uv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install the project
        run: uv sync --all-extras --dev 

      - name: Run Black (Code Formatting)
        run: uv run black --check .

      - name: Run Ruff (Linting)
        run: uv run ruff check .

      - name: Run MyPy (Static Type Checking)
        run: uv run mypy --explicit-package-bases src/

      - name: Run Pytest (Unit Tests)
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          uv run pytest tests --maxfail=5 --disable-warnings
